ribbon.client.name: application


app:
  port: ${PORT:8080}

# See CommonClientConfigKey in Netflix
example:
  retryable: true
  retryableStatusCodes: 502
  MaxAutoRetries: 3
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    consul:
      host: localhost
      port: 8500
      config.enabled: false
      enabled: true
      discovery:
        port: ${app.port}
        register: false
        heartbeat:
          enabled: true
        deregister: false
        register-health-check: true
      config:
        enabled: false


logging.level:
#  org.springframework.retry.backoff.ExponentialBackOffPolicy: DEBUG
#  org.springframework.retry.support.RetryTemplate: DEBUG